variable "owner" {}
variable "project" {}
variable "environment" {}
variable "costcentre" {}
variable "vpc_id" {}
variable "aws_key_name" {}
variable "aws_key_path" {}
variable "ami_id" {}
variable "instance_type" {}
variable "aws_region" {}
variable "app_sg" {}
