variable "owner" {}
variable "project" {}
variable "environment" {}
variable "costcentre" {}
variable "vpc_id" {}
variable "private_subnets_id" {}
variable "aws_key_name" {}
variable "aws_key_path" {}
variable "ami_id" {}
variable "availability_zones" {}
variable "aws_region" {}
variable "instance_type" {}
variable "amax" {}
variable "amin" {}
variable "adesired" {}
variable "lc_name" {}
variable "lc_id" {}
variable "role_app" {}
