driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.2
  - name: ubuntu-15.10
  - name: ubuntu-16.04

suites:
  - name: go 
    run_list: 
     - recipe[sbry::goapp]
     - recipe[sbry::consul]
  - name: lb
    run_list: 
     - recipe[sbru::consul]
     - recipe[sbry::consul-template]
     - recipe[sbry::lb]
